### ISSUE TITLE
Upgrade to React 15

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#371]
Should aim to upgrade this project to React 15. I just attempted to do it but there were problems. Mainly:

Changing the value of text inputs resulted in these errors:

> Warning: FormTextInput is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

There might be other issues too as I didn't test thoroughly for now.

**Comment by jkudish** [comment]
Related: https://github.com/Automattic/wp-calypso/pull/5116

**Comment by allendav** [comment]
Oops. We upgraded in https://github.com/Automattic/woocommerce-connect-client/commit/0f03bd3e48aa25b2915040fbca50b01ee5420a34 - will write a separate issue now for the controlled business.

**Comment by DanReyLop** [comment]
I don't remember any issue while upgrading, so that controlled component must have been fixed in the last few months :)

**Comment by allendav** [comment]
@DanReyLop - it is still happening: https://github.com/Automattic/woocommerce-connect-client/issues/484
